### ISSUE TITLE
subir archivos

### ISSUE THREAD

**Issue by matiasromantdf** [FrederickMontiel/SimpleRouter-php#2]
Hola, una consulta, como seria el tratamiento para subir archivos en un POST?

**Comment by FrederickMontiel** [comment]
Hola Matias, perdón, no he leído mis notificaciones...

Pero es tan fácil como tomar el formulario en JavaScript con un
`var formdata = new FormData(document.getElementById("myForm"));`

y luego por algún cliente http como `xmlhttprequest` o fetch enviar el `formdata`.

y obtener con:
`$req->files->name[0]`
`$req->files->type[0]`

o

`$req->files->name`
`$req->files->type`
